use std::env;

/*
 *  Environment configuration for the application.
 *  This struct holds various configuration values that are loaded from environment variables.
 *  - `env`: The environment in which the application is running (e.g., development, production).
 *  - `log_level`: The logging level for the application (e.g., info, debug
 *  - `discord_token`: The token for Discord bot authentication.
 *  - `discord_client_id`: The client ID for the Discord application.
 *  - `database_url`: The URL for the database connection.
 *  - `redis_url`: The URL for the Redis server connection.
 *  This struct is used to initialize the application with the necessary configuration values.
 *  It is typically loaded at the start of the application and used throughout its lifecycle.
*/
#[derive(Debug, Clone)]
pub struct EnvConfig {
    /*
        ! The environment in which the application is running
        ! This can be set to "development", "production", or any other custom environment.
        ! It is used to determine the configuration settings for the application.
    */
    pub env: String,
    /*
        ? The logging level for the application
        ? This can be set to "info", "debug", "error", etc.
        ? It determines the verbosity of the logs generated by the application.
        ? The default value is "info".
    */
    pub log_level: String,
    /*
        ! The token for Discord bot authentication
        ! This token is used to authenticate the bot with the Discord API.
        ! It is required for the bot to function properly and interact with Discord servers.
        ! The token should be kept secret and not shared publicly.
    */
    pub discord_token: String,
    // ! The client ID for the Discord application
    pub discord_client_id: String,
    // ! The URL for the database connection `postgres://user:password@host:port/<db>`
    pub database_url: String,
    // ! The URL for the Redis server connection `redis://user:password@host:port/<db>`
    pub redis_url: String,
}

impl Default for EnvConfig {
    fn default() -> Self {
        EnvConfig::new()
    }
}
/*
 *   `EnvConfig` is a struct that holds the configuration for the application.
 *   It is initialized with environment variables and provides methods to access these values.
 *   The `new` method initializes the struct with default values or values from environment variables.
 *   The `load` method is a convenience method to create a new instance of `EnvConfig`.
 *   The struct provides getter methods for each configuration value, allowing access to the environment,
 *   log level, Discord token, Discord client ID, database URL, and Redis URL.
*/
impl EnvConfig {
    fn new() -> EnvConfig {
        if let Err(e) = dotenvy::dotenv() {
            eprintln!("Warning: Could not load .env file: {}", e);
        }

        EnvConfig {
            env: env::var("ENV").unwrap_or_else(|_| "development".to_string()),
            log_level: env::var("LOG_LEVEL").unwrap_or_else(|_| "info".to_string()),
            discord_token: env::var("DISCORD_TOKEN").expect("DISCORD_TOKEN must be set"),
            discord_client_id: env::var("DISCORD_CLIENT_ID")
                .expect("DISCORD_CLIENT_ID must be set"),
            database_url: env::var("DATABASE_URL").expect("DATABASE_URL must be set"),
            redis_url: env::var("REDIS_URL").expect("REDIS_URL must be set"),
        }
    }
    // ! `load` is a convenience method to create a new instance of `EnvConfig`.
    pub fn load() -> EnvConfig {
        EnvConfig::new()
    }
    // ! Getter methods for each configuration value
    pub fn env(&self) -> &str {
        &self.env
    }
    // ? Returns the log level of the application
    pub fn log_level(&self) -> &str {
        &self.log_level
    }
    // ! Returns the Discord token for authentication
    pub fn discord_token(&self) -> &str {
        &self.discord_token
    }
    // ! Returns the Discord client ID for the application
    pub fn discord_client_id(&self) -> &str {
        &self.discord_client_id
    }
    // ! Returns the database URL for the application
    pub fn database_url(&self) -> &str {
        &self.database_url
    }
    // ! Returns the Redis URL for the application
    pub fn redis_url(&self) -> &str {
        &self.redis_url
    }
}
