[package]
name = "StarlightCore"
version = "0.1.0"
edition = "2024"

[lib]
name = "StarlightCore"
path = "src/lib.rs"

[[bin]]
name = "StarlightCore"
path = "src/main.rs"


[dependencies]
# Asynchronous runtime
async-trait = "0.1.58"
futures = "0.3"
futures-util = { version = "0.3.25", default-features = false }
tokio = { version = "1.45", features = ["full"] }
tracing = "0.1.37"
# Discord API
twilight = { version = "0.15.0" }
twilight-cache-inmemory = { version = "0.15.0" }
twilight-gateway = { version = "0.15.0" }
twilight-http = { version = "0.15.0" }
twilight-model = "0.15"
twilight-interactions = { version = "0.16.0" }
twilight-mention = { version = "0.16.0" }
twilight-util = { version = "0.16.0", features = ["builder", "snowflake"] }
# JSON serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
# Logging
log = "0.4"
env_logger = "0.10"
# Environment variables
dotenvy = { version = "0.15.7" }
# Error handling
anyhow = { version = "1.0" }
thiserror = { version = "2.0.12" }
# Databases
sea-orm = { version = "1.1.0", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
] }
vesper = "0.13.0"
