[package]
name = "starlight_api"
version = "0.1.0"
edition = "2024"

[dependencies]
# Database
sea-orm = { version = "1.1.0", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "macros" ] }
# Asynchronous runtime
async-trait = "0.1.58"
futures-util = { version = "0.3.25", default-features = false }
tokio = { version = "1.45", features = [ "full" ] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
# JSON serialization
serde = { version = "1.0", features = [ "derive" ] }
serde_json = { version = "1.0" }
serde_with = "3.0"
# Environment variables
dotenv = { version = "0.15" }
envy = "0.4"
# Error handling
anyhow = { version = "1.0" }
# Time handling
time = { version = "0.3", features = ["serde"] }
# Discord API
twilight-model = "0.16.0"

[dev-dependencies]
serde_test = "1.0"